# Generated by Django 4.2.1 on 2023-05-16 00:03

from django.db import migrations

def populate_task_status(apps, schema_editor):
    TaskStatus = apps.get_model('tasks', 'TaskStatus')
    TaskStatus.objects.bulk_create([
        TaskStatus(status='Completed'),
        TaskStatus(status='Assigned'),
        TaskStatus(status='Stuck'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskstatus_alter_task_task_status'),
    ]

    operations = [
        migrations.RunPython(populate_task_status),
    ]
