# Generated by Django 4.2.1 on 2023-05-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_jobtype_timeentry_alter_task_task_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_kind',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
