# Generated by Django 4.2.1 on 2023-05-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_task_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_kind',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.jobtype'),
        ),
    ]
