# Generated by Django 4.2.1 on 2023-05-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_task_description_alter_timeentry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='AdminRate',
            field=models.DecimalField(decimal_places=2, default='50.00', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='AssociateDesignerRate',
            field=models.DecimalField(decimal_places=2, default='50.00', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='LeadDesignerRate',
            field=models.DecimalField(decimal_places=2, default='50.00', max_digits=5),
            preserve_default=False,
        ),
    ]
