# Generated by Django 4.2.1 on 2023-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_adminrate_client_admin_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
