# Generated by Django 4.2.1 on 2023-05-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_remove_timeentry_job_type_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='lead_designer_rate',
            new_name='junior_designer_rate',
        ),
        migrations.AddField(
            model_name='client',
            name='principal_designer_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='senior_designer_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
