# Generated by Django 4.2.1 on 2023-05-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_rename_lead_designer_rate_client_junior_designer_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='zack_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
