# Generated by Django 4.2.1 on 2023-05-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_client_zack_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_notes',
            field=models.TextField(default=None, null=True),
        ),
    ]
